name: exercise 3 variables

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repo
        uses: actions/checkout@v4
      - name: build-deploy
        uses: ./github/deploy/action.yml
